Repository woowa-techcamp-2020/todo-13, pull requests merged in 2020-07, with the labels that each got.

#17 Add component skeleton
  client/public/f9a9d9533987c9f6196869dd88722e4c.jpg
  client/public/index.html
  client/src/App.js
  client/src/components/Card.js
  client/src/components/Column.js
  client/src/components/Dashboard.js
  client/src/components/Header.js
  client/src/components/Item.js
  client/src/components/Modal.js
  client/src/components/Popup.js
  client/src/components/Sidebar.js
  client/src/index.js
  client/src/style.css
Labels: FE, setting

#18 Add sass loader in webpack config
  client/package-lock.json
  client/package.json
  client/src/index.js
  client/src/style.scss
  client/webpack.config.js
Labels: FE, setting

#19 Header, Dashboard, Column, Card 마크업
  client/src/components/Card.js
  client/src/components/Card.scss
  client/src/components/Column.js
  client/src/components/Column.scss
  client/src/components/Dashboard.js
  client/src/components/Dashboard.scss
  client/src/components/Header.js
  client/src/components/Header.scss
  client/src/style.css
  client/src/style.scss
  client/src/utils/util.js
Labels: FE, feature

#20 서버 및 데이터베이스 세팅
  .gitignore
  server/Dockerfile
  server/app.js
  server/docker-compose.yml
  server/package-lock.json
  server/package.json
  server/sql_scripts/createTable.sql
  server/sql_scripts/insertCard.sql
  server/utf8.cnf
Labels: BE, feature, setting

#22 Remove console log in server
  .gitignore
  server/app.js
Labels: bug

#21 팝업 컴포넌트 추가 및 drag and drop 실험 추가
  client/src/components/Card.js
  client/src/components/Card.scss
  client/src/components/Column.js
  client/src/components/Dashboard.js
  client/src/components/Header.js
  client/src/components/Popup.js
  client/src/components/Popup.scss
  client/src/utils/messages.js
  client/src/utils/util.js
Labels: FE, feature

#31 Dummy Data 모듈 만들기
  client/src/Data.js
  client/src/components/Dashboard.js
  server/Dockerfile
  server/config/utf8mb4.cnf
  server/docker-compose.yml
  server/sql_scripts/createTable.sql
  server/sql_scripts/insertCard.sql
  server/utf8.cnf
Labels: BE, FE, feature, setting

#33 Modal 컴포넌트 스타일 추가와 기본 기능 구현
  client/src/components/Card.js
  client/src/components/Column.js
  client/src/components/Modal.js
  client/src/components/Modal.scss
  client/src/components/Popup.js
  client/src/components/Popup.scss
  client/src/utils/messages.js
  client/src/utils/util.js
Labels: FE, feature

#34 Server 스켈레톤 구현
  server/DAO/cardDAO.js
  server/api.http
  server/app.js
  server/controllers/cardController.js
  server/models/Card.js
  server/package-lock.json
  server/package.json
  server/routes/cardRouter.js
  server/services/cardService.js
Labels: BE, feature

#35 Client Util 함수 단위테스트 작성
  client/babel.config.js
  client/package-lock.json
  client/package.json
  client/src/test/utils/utils.test.js
  server/app.js
  server/package-lock.json
  server/package.json
Labels: FE, test

#36 Sidebar 스타일 및 애니메이션 구현
  client/public/index.html
  client/src/App.js
  client/src/components/Header.js
  client/src/components/Item.scss
  client/src/components/Modal.js
  client/src/components/Modal.scss
  client/src/components/Popup.scss
  client/src/components/Sidebar.js
  client/src/components/Sidebar.scss
Labels: FE, feature

#37 POST card API 구현
  server/DAO/cardDAO.js
  server/Domain/Card.js
  server/api.http
  server/app.js
  server/controllers/cardController.js
  server/db.js
  server/models/Card.js
  server/package-lock.json
  server/package.json
  server/routes/apiRouter.js
  server/routes/cardRouter.js
  server/services/cardService.js
Labels: BE, feature

#38 컴포넌트 스타일 수정
  client/src/components/Card.js
  client/src/components/Card.scss
  client/src/components/Column.js
  client/src/components/Column.scss
  client/src/components/Dashboard.scss
  client/src/components/Header.scss
  client/src/style.scss
Labels: FE, enhancement, feature

#39 Server 3 Layers 리팩토링
  server/DAO/cardDAO.js
  server/Repository/CardRepository.js
  server/controllers/cardController.js
  server/db.js
  server/package-lock.json
  server/package.json
  server/routes/cardRouter.js
  server/services/cardService.js
  server/test/CardRepository.spec.js
Labels: BE, refactoring

#40 GET one card api 구현
  server/Repository/CardRepository.js
  server/api.http
  server/controllers/cardController.js
  server/package-lock.json
  server/routes/cardRouter.js
  server/services/cardService.js
Labels: BE, feature

#41 DELETE card api 추가
  server/Repository/CardRepository.js
  server/api.http
  server/controllers/cardController.js
  server/routes/cardRouter.js
  server/services/cardService.js
Labels: BE, feature

#42 PUT card api 추가
  server/Repository/CardRepository.js
  server/api.http
  server/controllers/cardController.js
  server/routes/cardRouter.js
  server/services/cardService.js
Labels: BE, feature

#43 <Item> 컴포넌트 개발
  client/src/components/Dashboard.js
  client/src/components/Item.js
  client/src/components/Item.scss
  client/src/components/Sidebar.js
  client/src/components/Sidebar.scss
Labels: FE, feature

#46 User, Activity 테이블 생성 스크립트 추가
  server/sql_scripts/createTable.sql
  server/sql_scripts/createTables.sql
  server/sql_scripts/insertCard.sql
Labels: BE, feature

#48 함수형 컴포넌트로 리팩토링 및 기능 구현
  client/babel.config.js
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Data.js
  client/src/__mocks__/fileMock.js
  client/src/__tests__/components/App.test.js
  client/src/__tests__/components/Item.test.js
  client/src/__tests__/utils/utils.test.js
  client/src/components/AddCardForm.js
  client/src/components/AddCardForm.scss
  client/src/components/Card.js
  client/src/components/Card.scss
  client/src/components/Column.js
  client/src/components/Column.scss
  client/src/components/Dashboard.js
  client/src/components/Header.js
  client/src/components/Header.scss
  client/src/components/Item.js
  client/src/components/Modal.js
  client/src/components/Modal.scss
  client/src/components/Popup.js
  client/src/components/Popup.scss
  client/src/components/Sidebar.js
  client/src/components/Sidebar.scss
  client/src/index.js
  client/src/store.js
  client/src/utils/util.js
Labels: FE, feature, refactoring

#49 컬럼 제목 수정 기능 구현
  client/src/components/AddCardForm.js
  client/src/components/Card.js
  client/src/components/Dashboard.js
  client/src/components/Modal.js
  client/src/store.js
Labels: FE, feature

#50 Activity 라우터, 컨트롤러, 서비스, 레포지토리, 도메인 구현
  server/Domain/Activity.js
  server/Repository/ActivityRepository.js
  server/api.http
  server/controllers/activity-controller.js
  server/routes/activity-router.js
  server/routes/apiRouter.js
  server/services/activity-service.js
Labels: BE, feature

#52 AddCardForm 컴포넌트 Add 버튼 비활성화 기능 구현
  client/src/components/AddCardForm.js
  client/src/components/Modal.js
Labels: FE, feature

#55 Card 도메인 리팩토링
  server/Repository/CardRepository.js
  server/api.http
  server/app.js
  server/controllers/activity-controller.js
  server/controllers/card-controller.js
  server/domain/activity.js
  server/domain/card.js
  server/repository/activity-repository.js
  server/repository/card-repository.js
  server/routes/api-router.js
  server/routes/card-router.js
  server/services/card-service.js
  server/sql_scripts/createTables.sql
  server/sql_scripts/insertCard.sql
Labels: BE, refactoring

#57 Client 배포 스크립트 추가
  build.sh
  client/public/index_bundle.js
  server/public/index_bundle.js
Labels: BE, FE, feature

#58 Client 이벤트와 Server api 연결
  client/public/index_bundle.js
  client/src/components/Item.js
  client/src/services/activityService.js
  client/src/services/cardService.js
  client/src/store.js
  server/api.http
  server/controllers/activity-controller.js
  server/controllers/card-controller.js
  server/domain/activity.js
  server/domain/card.js
  server/public/index_bundle.js
  server/repository/activity-repository.js
  server/repository/card-repository.js
  server/routes/card-router.js
  server/services/card-service.js
  server/sql_scripts/createTables.sql
Labels: BE, FE

#56 drag and drop 구현
  client/src/Data.js
  client/src/components/Card.js
  client/src/components/Card.scss
  client/src/components/Column.js
  client/src/components/Column.scss
  client/src/components/CopyCard.js
  client/src/components/CopyCard.scss
  client/src/components/Dashboard.js
  client/src/components/Dashboard.scss
  client/src/components/Header.js
  client/src/components/Sidebar.js
  client/src/components/Sidebar.scss
  client/src/store.js
  client/src/style.scss
Labels: FE, feature

#59 Move card api 구현
  client/public/index_bundle.js
  client/src/services/cardService.js
  client/src/store.js
  server/card.http
  server/controllers/card-controller.js
  server/public/index_bundle.js
  server/repository/card-repository.js
  server/routes/card-router.js
  server/services/card-service.js
Labels: BE, feature

#62 Client 카드 수정, 삭제 액션과 Backend api 호출 연결
  client/public/index_bundle.js
  client/src/components/Dashboard.js
  client/src/services/cardService.js
  client/src/store.js
  server/api.http
  server/controllers/card-controller.js
  server/public/index_bundle.js
  server/repository/activity-repository.js
  server/repository/card-repository.js
  server/services/card-service.js
Labels: BE, feature

#63 Frontend 카드 drag and drop과 Backend api 호출 연결
  client/public/index_bundle.js
  client/src/components/Column.js
  client/src/components/Dashboard.js
  client/src/services/cardService.js
  client/src/store.js
  server/controllers/card-controller.js
  server/public/index_bundle.js
  server/repository/card-repository.js
  server/services/card-service.js
Labels: BE, FE, feature

#65 move card api 버그 수정
  client/src/services/cardService.js
Labels: FE, bug

#64 <Item> 컴포넌트 시간형식 수정
  .gitignore
  client/public/index_bundle.js
  client/src/components/Header.js
  client/src/services/activityService.js
  client/src/store.js
  client/src/utils/util.js
  server/db.js
  server/public/index_bundle.js
  server/repository/card-repository.js
Labels: FE, enhancement

#66 card drag and drop시 마우스가 벗어 났을 때 처리
  client/src/components/Dashboard.js
Labels: FE, enhancement, feature

#68 store.js 오류 수정
  client/src/components/Dashboard.js
  client/src/store.js
  server/repository/card-repository.js
Labels: FE, bug

#69 moveCard 서비스에 activity log 추가
  client/src/components/Dashboard.js
  server/controllers/card-controller.js
  server/repository/card-repository.js
  server/services/card-service.js
Labels: BE, FE, bug, feature

#70 Webpack development and production 설정
  build.sh
  client/package-lock.json
  client/package.json
  client/webpack.common.js
  client/webpack.dev.js
  client/webpack.prod.js
Labels: FE, enhancement, feature

#71 Add express middleware cors
  server/app.js
  server/package-lock.json
  server/package.json
Labels: BE, enhancement

#72 컬럼 제목 수정 기능 구현
  client/src/components/Column.js
  client/src/components/Dashboard.js
  client/src/services/columnService.js
  client/src/store.js
  server/card.http
  server/controllers/activity-controller.js
  server/controllers/column-controller.js
  server/db.js
  server/domain/column.js
  server/repository/card-repository.js
  server/repository/column-repository.js
  server/routes/activity-router.js
  server/routes/api-router.js
  server/routes/column-router.js
  server/services/activity-service.js
  server/services/column-service.js
Labels: BE, FE, feature

#73 Add pm2 process managing package
  server/package.json
Labels: BE, enhancement

#74 Client API 엔드포인트 환경변수 분리
  client/package-lock.json
  client/package.json
  client/src/services/activityService.js
  client/src/services/cardService.js
  client/src/services/columnService.js
  client/src/store.js
  client/webpack.common.js
  server/db.js
Labels: FE, enhancement

#75 UI 스타일 개선
  client/public/favicon-16x16.png
  client/public/favicon-32x32.png
  client/public/index.html
  client/src/components/Card.js
  client/src/components/Card.scss
  client/src/components/Column.js
  client/src/components/Column.scss
  client/src/components/CopyCard.scss
  client/src/components/Dashboard.js
  client/src/components/Header.js
  client/src/components/Header.scss
  client/src/components/Item.js
  client/src/components/Item.scss
  client/src/components/Modal.js
  client/src/components/Modal.scss
  client/src/components/Popup.scss
  client/src/components/Sidebar.js
  client/src/components/Sidebar.scss
  client/src/style.scss
  server/public/favicon-16x16.png
  server/public/favicon-32x32.png
  server/public/index.html
Labels: FE, enhancement

#77 Mock 로그인 구현
  client/src/components/AddCardForm.js
  client/src/components/Column.js
  client/src/components/Header.js
  client/src/components/Header.scss
  client/src/components/Modal.js
  client/src/components/Popup.js
  client/src/store.js
  client/src/style.scss
  server/controllers/card-controller.js
  server/db.js
Labels: FE, feature

#78 Header UI style 개선
  client/src/components/Dashboard.js
  client/src/components/Header.js
  client/src/components/Header.scss
  client/src/components/Item.scss
  client/src/components/Sidebar.scss
Labels: FE, bug, enhancement

#76 README.md 개선
  README.md
Labels: documentation, enhancement, feature

#79 Server 에러 처리 리팩토링
  client/src/components/Dashboard.js
  client/src/components/Header.js
  client/src/components/Sidebar.js
  client/src/store.js
  server/api.http
  server/app.js
  server/controllers/activity-controller.js
  server/controllers/card-controller.js
  server/controllers/column-controller.js
  server/error.js
  server/public/notFound.html
  server/repository/activity-repository.js
  server/repository/card-repository.js
  server/repository/column-repository.js
  server/services/activity-service.js
  server/services/card-service.js
  server/services/column-service.js
Labels: BE, refactoring

#81 Popup box 사이즈 수정
  client/src/components/Popup.scss
Labels: FE, bug
